import esbuild from "esbuild";
import process from "process";

// Node.js 內建模組清單（取代 builtin-modules 套件，消除 community review
// "builtin-modules should be replaced" 警告；esbuild 對 external 前綴
// 套用 node: 前綴規則，裸名稱與 node: 名稱皆需列出以涵蓋兩種 import 寫法）。
const nodeBuiltinModules = [
  "assert", "assert/strict", "async_hooks", "buffer", "child_process",
  "cluster", "console", "constants", "crypto", "dgram",
  "diagnostics_channel", "dns", "dns/promises", "domain", "events",
  "fs", "fs/promises", "http", "http2", "https",
  "inspector", "module", "net", "os", "path",
  "path/posix", "path/win32", "perf_hooks", "process", "punycode",
  "querystring", "readline", "readline/promises", "repl", "stream",
  "stream/consumers", "stream/promises", "stream/web", "string_decoder", "timers",
  "timers/promises", "tls", "trace_events", "tty", "url",
  "util", "util/types", "v8", "vm", "wasi",
  "worker_threads", "zlib",
];
const builtins = [
  ...nodeBuiltinModules,
  ...nodeBuiltinModules.map((name) => `node:${name}`),
];

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: true,
  treeShaking: true,
  outfile: "main.js",
  minify: false,
});

if (prod) {
  await context.rebuild();
  await context.dispose();
  process.exit(0);
} else {
  await context.watch();
}
